services:
  # O Templo do Saber
  postgres:
    image: postgres:15-alpine
    container_name: templo_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - templo

  # O Observatório Cósmico
  metabase:
    image: metabase/metabase:latest
    container_name: observatorio_metabase
    depends_on:
      - postgres
    ports:
      - "3001:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_DB}
      MB_DB_PORT: 5432
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: postgres
    restart: unless-stopped
    networks:
      - templo

  # Os Portais de Coleta e Orquestração
  mage:
    image: mageai/mageai:latest
    container_name: portais_mage
    command: mage start projeto_lumen
    depends_on:
      - postgres
    ports:
      - "6789:6789"
    volumes:
      - ./mage_workspace:/home/src/
    restart: unless-stopped
    networks:
      - templo

  # O Laboratório do Alquimista
  jupyterlab:
    image: jupyter/datascience-notebook
    container_name: laboratorio_jupyter
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - "8888:8888"
    command: start-notebook.sh --NotebookApp.token=''
    networks:
      - templo
    depends_on:
      - mage
    restart: unless-stopped

volumes:
  postgres_data:
    name: lumen_postgres_data

networks:
  templo:
